version: '3.8'

services:

 # ================= API =================
 api:
  build: .
  ports:
   - "8000:8000"
  environment:
   - API_HOST=0.0.0.0
   - API_PORT=8000
   - MODELS_DIR=/app/models
  volumes:
   - ./models:/app/models
   - ./data:/app/data
  networks:
   - fraud-network
  healthcheck:
   test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
   interval: 30s
   timeout: 10s
   retries: 3

 # ================= DASHBOARD =================
 dashboard:
  build: .
  command: streamlit run src/bi/dashboard.py --server.port=8501 --server.address=0.0.0.0
  ports:
   - "8501:8501"
  environment:
   - API_URL=http://api:8000
  depends_on:
   - api
  networks:
   - fraud-network
  volumes:
   - ./src:/app/src
   - ./data:/app/data

 # ================= POSTGRES =================
 postgres:
  image: postgres:15
  environment:
   - POSTGRES_USER=fraud_user
   - POSTGRES_PASSWORD=fraud_password
   - POSTGRES_DB=fraud_detection
  ports:
   - "5432:5432"
  volumes:
   - postgres_data:/var/lib/postgresql/data
  networks:
   - fraud-network

 # ================= ZOOKEEPER =================
 zookeeper:
  image: confluentinc/cp-zookeeper:7.5.0
  container_name: zookeeper
  environment:
   ZOOKEEPER_CLIENT_PORT: 2181
   ZOOKEEPER_TICK_TIME: 2000
  ports:
   - "2181:2181"
  networks:
   - fraud-network

 # ================= KAFKA =================
 kafka:
  image: confluentinc/cp-kafka:7.5.0
  container_name: kafka
  depends_on:
   - zookeeper
  ports:
   - "9092:9092"
  environment:
   KAFKA_BROKER_ID: 1
   KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
   KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
   KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
  networks:
   - fraud-network

# ================= NETWORKS =================
networks:
 fraud-network:
  driver: bridge

# ================= VOLUMES =================
volumes:
 postgres_data: